# Format of using: try - except:

try:
    #risky code: In this section our actual code logic will be added
    x = int("abc")                  # This will throw a ValueError exception
except ValueError as e:             
    # Here ValueError is a Class in the Exception Class
    # e will be the object of ValueError Class
    # As we are creating an object of a Class, it will call its __init__ method automatically
    print("Caught ValueError:", e) 
# Here we are calling the object e

# Output: Caught ValueError: invalid literal for int() with base 10: 'abc' 
    # 1. Caught ValueError is the string passed in the print statement
    # 2. invalid literal for int() with base 10: 'abc' - This message is printed as per the defined in the __init__ method of ValueError - Exception - BaseException 
    # (This string is generated by the Compiler/ OS)

# Without specifying an error:
try:
    name = "Atharva"
except:
    print("Something went wrong!")
    
    